name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install
          npm audit fix  # Pour corriger les vulnérabilités, si nécessaire

      - name: Build
        run: npm run build

      - name: Deploy
        uses: appleboy/ssh-action@v3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/rickandmorty
            
            git fetch --all
            git reset --hard origin/master
            git pull origin master
            npm install --production
            npm run build
