name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd /var/www/html/rickandmorty
            
            # S'assurer que le répertoire existe
            if [ ! -d "/var/www/html/rickandmorty" ]; then
              mkdir -p /var/www/html/rickandmorty
            fi
            
            # Cloner le dépôt ou mettre à jour s'il existe déjà
            git clone https://github.com/yourusername/yourrepo.git . || git pull
            
            # Installer les dépendances
            npm install
            
            # Construire le projet
            npm run build
            
            # Redémarrer Apache
            systemctl restart apache2
